labels:
  - name: bug
    color: ff0000
    description: 🐞 Something is broken
  - name: enhancement
    color: 00ff00
    description: ✨ New feature or improvement
  - name: documentation
    color: 1e90ff
    description: 📚 Docs updates or additions
  - name: question
    color: ffa500
    description: ❓ User or developer question
  - name: help wanted
    color: 8a2be2
    description: 🙋‍♂️ Needs community help
  - name: in progress
    color: 1abc9c
    description: 🔄 Work currently in progress
  - name: high priority
    color: ff4500
    description: ⚡ Must be addressed ASAP
  - name: low priority
    color: 808080
    description: 💤 Not urgent
  - name: duplicate
    color: c0c0c0
    description: 📑 Duplicate of another issue
  - name: wontfix
    color: 000000
    description: ❌ Won't fix or obsolete
